```{r prematch-balance}
# These are the covariates of interest and will be used for matching.
covariates <- c("sex", "age", "smoke", "fnstatus2", "hxcopd", "steroid", "wtloss", "bleeddis", "transfus", "asaclas")

# Set data covariate variable labels
data <- data %>%
   labelled::set_variable_labels(
      sex = "Male (%)", 
      age = "Age (mean (SD))", 
      smoke = "Smoking history (%)", 
      fnstatus2 = "Functionally independent (%)", 
      hxcopd = "History of COPD (%)", 
      steroid = "Steroid use (%)", 
      wtloss = ">10% weight loss (%)", 
      bleeddis = "Bleeding disorder (%)", 
      transfus = "Preoperative transfusion (%)", 
      asaclas = "ASA class (%)")

# Create pre-match balance assessment table data frame.
tab_prematchbalance <- tableone::CreateTableOne(vars = covariates, strata = "group", data = data)
   
```

```{r complete-cases}
# The match requires only complete data. Select for only the columns we care about then get only complete cases.
data <- data %>%
  dplyr::select(caseid, group, sex, age, bmi, smoke, fnstatus2, dyspnea, hxcopd, steroid, wtloss, bleeddis, transfus, asaclas, supinfec, wndinfd, orgspcssi, othdvt, pulembol, reintub, failwean, renainsf, oprenafl, col_anastomotic, col_unplanned_conversion, ostomy, reoperation, readmission, optime, tothlos) %>%
  dplyr::filter(complete.cases(.))
```

```{r match}
# Propensity score match 
match <- MatchIt::matchit(group ~ sex + age + smoke + fnstatus2 + hxcopd + steroid + wtloss + bleeddis + transfus + asaclas, data = data, ratio = 2)

# Extract data-frame of matched data
match_data <- MatchIt::match.data(match)
```

```{r postmatch-balance}
# Create post-match balance assessment table.
tab_postmatchbalance <- tableone::CreateTableOne(vars = covariates, strata = "group", data = match_data)
```

```{r postmatch-outcomes-discrete}
# Create post-match discrete outcomes data frame using rate_result (package function, see R/functions.R)
postmatch_discrete <- dplyr::bind_rows(
   match_data %>% rate_result(col_anastomotic, `Anastomotic Leak`),
   match_data %>% rate_result(col_unplanned_conversion, Conversion),
   match_data %>% rate_result(ostomy, Ostomy),
   match_data %>% dplyr::mutate(ssi = supinfec|wndinfd|orgspcssi) %>% rate_result(ssi, `Overall SSI`),
   match_data %>% rate_result(supinfec, `Superficial SSI`),
   match_data %>% rate_result(wndinfd, `Deep SSI`),
   match_data %>% rate_result(orgspcssi, `Organ-space SSI`),
   match_data %>% rate_result(readmission, Readmission),
   match_data %>% rate_result(reoperation, Reoperation)
)
```

```{r postmatch-outcomes-continuous}
# Create post-match continuous outcomes data frame using cont_result (package function, see R/functions.R)
postmatch_continuous <- dplyr::bind_rows(
   match_data %>% cont_result(optime, `Operative time (min)`),
   match_data %>% cont_result(tothlos, `LOS (days)`)
)
```

```{r manuscript-variables}
# Number of control and obese patients meeting inclusion criteria prior to matching.
prematch_control_n <- dplyr::count(data, group)[[1, 2]]
prematch_obese_n <- dplyr::count(data, group)[[2, 2]]

# Calculate the mean BMI and standard deviation for each group prior to matching.
prematch_bmis <- data %>%
   dplyr::group_by(group) %>%
   dplyr::summarise(avg = mean(bmi),
                    sd = sd(bmi))
prematch_control_bmi <- round(prematch_bmis[[1, 'avg']], digits = 1)
prematch_obese_bmi <- round(prematch_bmis[[2,'avg']], digits = 1)
prematch_control_sd <- round(prematch_bmis[[1,'sd']], digits = 1)
prematch_obese_sd <- round(prematch_bmis[[2,'sd']], digits = 1)
prematch_control_bmisd <- glue::glue('{prematch_control_bmi} ± {prematch_control_sd}')
prematch_obese_bmisd <- glue::glue('{prematch_obese_bmi} ± {prematch_obese_sd}')

# Number of control and obese patients after the match.
postmatch_control_n <- dplyr::count(match_data, group)[[1, 2]]
postmatch_obese_n <- dplyr::count(match_data, group)[[2, 2]]

# Specific post-match results of interest
# Conversion to open
postmatch_control_convtoopen <- glue::glue("{postmatch_discrete[5, 'Rate (%)']}%")
postmatch_obese_convtoopen <- glue::glue("{postmatch_discrete[6, 'Rate (%)']}%")
postmatch_convtoopen_p <- postmatch_discrete[6, 'p']
postmatch_convtoopen <- glue::glue("{postmatch_obese_convtoopen} vs {postmatch_control_convtoopen}, p = {postmatch_convtoopen_p}")

# Readmission
postmatch_control_readm <- glue::glue("{postmatch_discrete[23, 'Rate (%)']}%")
postmatch_obese_readm <- glue::glue("{postmatch_discrete[24, 'Rate (%)']}%")
postmatch_readm_p <- postmatch_discrete[24, 'p']
postmatch_readm <- glue::glue("{postmatch_obese_readm} vs {postmatch_control_readm}, p = {postmatch_readm_p}")

# Operative time
postmatch_control_optime <- glue::glue("{postmatch_continuous[2, 'Mean']} minutes")
postmatch_obese_optime <- glue::glue("{postmatch_continuous[3, 'Mean']} minutes")
postmatch_optime_p <- postmatch_continuous[3, 'p']
postmatch_optime <- glue::glue("{postmatch_obese_optime} vs {postmatch_control_optime}, p = {postmatch_optime_p}")

# Leak rate
postmatch_control_leak <- glue::glue("{postmatch_discrete[3, 'Rate (%)']}%")
postmatch_obese_leak <- glue::glue("{postmatch_discrete[3, 'Rate (%)']}%")
postmatch_leak_p <- postmatch_discrete[3, 'p']
```
